In [29]:
import numpy as np
import pandas as pd

In [30]:
arr1=np.arange(1,11)
print(arr1)
arr2=arr1.reshape(2,5)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
arr3=np.arange(1,21)
arr4=arr3[5:15]
print(arr4)

[ 6  7  8  9 10 11 12 13 14 15]


In [32]:
print("Mean:",np.mean(arr3))
print("Median:",np.median(arr3))
print("Standard Deviation:",np.std(arr3))

Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [33]:
arr_x=np.array([[2,3,4,5],[3,4,5,6],[7,6,5,3]])
print("array x:",arr_x)
print("shape of x:",arr_x.shape)
arr_y=np.array([1,2,3,4])
print("\narray y:",arr_y)
print("shape of y",arr_y.shape)
arr_add=arr_x - arr_y
print("\nResult array:")
print(arr_add)

array x: [[2 3 4 5]
 [3 4 5 6]
 [7 6 5 3]]
shape of x: (3, 4)

array y: [1 2 3 4]
shape of y (4,)

Result array:
[[ 1  1  1  1]
 [ 2  2  2  2]
 [ 6  4  2 -1]]


In [34]:
data=pd.DataFrame({"Name":["Anu","Balu","Catherine","Denver","Joji","Banu","Xavier","Jane","Lolitta","Kayal"],"Age":[20,30,45,65,22,23,77,31,21,24],"Gender":['F','M','F','M','M','F','M','F','F','F']})
print(data)

        Name  Age Gender
0        Anu   20      F
1       Balu   30      M
2  Catherine   45      F
3     Denver   65      M
4       Joji   22      M
5       Banu   23      F
6     Xavier   77      M
7       Jane   31      F
8    Lolitta   21      F
9      Kayal   24      F


In [35]:
data["Occupation"]=["Programmer","Analyst","Manager","Manager","Programmer","Analyst","Manager","Programmer","Analyst","Analyst"]
print(data)

        Name  Age Gender  Occupation
0        Anu   20      F  Programmer
1       Balu   30      M     Analyst
2  Catherine   45      F     Manager
3     Denver   65      M     Manager
4       Joji   22      M  Programmer
5       Banu   23      F     Analyst
6     Xavier   77      M     Manager
7       Jane   31      F  Programmer
8    Lolitta   21      F     Analyst
9      Kayal   24      F     Analyst


In [36]:
print(data[(data["Age"]>=30)])

        Name  Age Gender  Occupation
1       Balu   30      M     Analyst
2  Catherine   45      F     Manager
3     Denver   65      M     Manager
6     Xavier   77      M     Manager
7       Jane   31      F  Programmer


In [37]:
data.to_csv("Details.csv",index=False)

In [38]:
data1=pd.read_csv("Details.csv")
print(data1.head())

        Name  Age Gender  Occupation
0        Anu   20      F  Programmer
1       Balu   30      M     Analyst
2  Catherine   45      F     Manager
3     Denver   65      M     Manager
4       Joji   22      M  Programmer
